name: "my_resort_project"
version: "1.0.0"
config-version: 2

profile: "my_resort_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_resort_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
